# Generated by Django 4.2.3 on 2023-07-17 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='pro_id', primary_key=True, serialize=False, verbose_name='Id')),
                ('key', models.CharField(db_column='pro_key', max_length=50, verbose_name='Key')),
                ('name', models.CharField(db_column='pro_name', max_length=50, verbose_name='Name')),
                ('price', models.FloatField(db_column='pro_price', verbose_name='Price')),
                ('description', models.CharField(db_column='pro_description', verbose_name='Description')),
                ('user', models.ForeignKey(db_column='pro_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(db_column='cli_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='cli_name', max_length=500, verbose_name='Name')),
                ('dni', models.CharField(db_column='cli_dni', max_length=20, verbose_name='dni')),
                ('type_dni', models.CharField(db_column='cli_type', max_length=2, verbose_name='TYPE_DNI')),
                ('address', models.CharField(db_column='cli_address', max_length=500, verbose_name='Address')),
                ('phone', models.CharField(db_column='cli_phone', max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(db_column='cli_email', max_length=1000, verbose_name='Email')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.AutoField(db_column='cat_id', primary_key=True, serialize=False)),
                ('image', models.ImageField(db_column='cat_image', upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.product')),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalogs',
            },
        ),
        migrations.CreateModel(
            name='Bilding',
            fields=[
                ('id', models.AutoField(db_column='bil_id', primary_key=True, serialize=False, verbose_name='Id')),
                ('date', models.DateField(auto_now_add=True, db_column='bil_date', verbose_name='Date')),
                ('secuence', models.IntegerField(db_column='bil_secuence', verbose_name='Secuence')),
                ('client', models.ForeignKey(db_column='bil_client', on_delete=django.db.models.deletion.CASCADE, to='ventas.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Bilding',
                'verbose_name_plural': 'Bildings',
            },
        ),
    ]
