# Generated by Django 4.2.3 on 2023-07-17 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilding',
            name='user',
            field=models.ForeignKey(db_column='bil_user', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='iva',
            field=models.CharField(choices=[('1', '0%'), ('2', '12%')], db_column='pro_iva', default=1, max_length=1, verbose_name='IVA'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bilding',
            name='id',
            field=models.AutoField(db_column='bil_id', db_index=True, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='id',
            field=models.AutoField(db_column='cat_id', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(db_column='cli_id', db_index=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(db_column='pro_id', db_index=True, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.CreateModel(
            name='DetailBilding',
            fields=[
                ('id', models.AutoField(db_column='dbi_id', db_index=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_unit', models.FloatField(db_column='dbi_price_unit', verbose_name='Price unit')),
                ('amount', models.FloatField(db_column='dbi_amount', verbose_name='Amount')),
                ('bilding', models.ForeignKey(db_column='dbi_bilding', on_delete=django.db.models.deletion.CASCADE, related_name='detail_bilding', to='ventas.bilding', verbose_name='Bilding')),
            ],
            options={
                'verbose_name': 'Detail bilding',
                'verbose_name_plural': 'Detail bildings',
            },
        ),
        migrations.CreateModel(
            name='CarShop',
            fields=[
                ('id', models.AutoField(db_column='car_id', db_index=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('amount', models.FloatField(db_column='car_amount', default=1, verbose_name='Amount')),
                ('product', models.ForeignKey(db_column='car_product', on_delete=django.db.models.deletion.CASCADE, to='ventas.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Carshop',
                'verbose_name_plural': 'Carshop',
            },
        ),
    ]
