# Generated by Django 4.2.3 on 2023-07-17 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_bilding_user_product_iva_alter_bilding_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog', to='ventas.product'),
        ),
    ]
