# Generated by Django 4.2.3 on 2023-07-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_catalogproduct_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(db_column='pub_id', db_index=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publisher', models.CharField(db_column='pub_publisher', max_length=500, verbose_name='Publisher ID facebook')),
            ],
        ),
    ]
