# Generated by Django 4.2.3 on 2023-07-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.AddField(
            model_name='product',
            name='id_publisher',
            field=models.CharField(db_column='pro_publisher', default=1, max_length=500, verbose_name='Publisher ID facebook'),
            preserve_default=False,
        ),
    ]
