# Generated by Django 4.2.3 on 2023-07-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_delete_publisher_product_id_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_publisher',
            field=models.CharField(db_column='pro_publisher', default=None, max_length=500, null=True, verbose_name='Publisher ID facebook'),
        ),
    ]
