# Generated by Django 4.2.3 on 2023-07-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_alter_product_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_publisher',
            field=models.CharField(blank=True, db_column='pro_publisher', default=None, max_length=500, null=True, verbose_name='Publisher ID facebook'),
        ),
    ]
