# Generated by Django 4.2.3 on 2023-07-30 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0008_alter_product_id_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='client',
            field=models.ForeignKey(db_column='car_client', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client'),
            preserve_default=False,
        ),
    ]
