# Generated by Django 4.2.3 on 2023-07-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_carshop_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilding',
            name='user',
        ),
    ]
